
export const RESERVED_SLUGS = [
    'dashboard',
    'login',
    'signup',
    'admin',
    'api',
    'app',
    'settings',
    'account',
    'profile',
    'config',
    'logout',
    'perfil',
    'usuarios',
    'links',
    'help',
    'support',
    'suporte',
    'contact',
    'contato',
    'about',
    'blog',
    'legal',
    'privacy',
    'privacidade',
    'terms',
    'termos',
    'onboarding',
    'planos',
    'pricing',
    'cadastro',
    'entrar',
    'root',
    'index',
    'home',
    'search',
    'explore',
    'notifications',
    'messages',
    'auth',
    'register',
    'recover',
    'reset-password',
    'robots.txt',
    'sitemap.xml',
    'favicon.ico',
    'assets',
    'static',
    'public',
    'images',
    'null',
    'undefined'
];


export const isReservedSlug = (slug) => {
    return RESERVED_SLUGS.includes(slug.toLowerCase().trim());
};
